In [1]:
import numpy as np
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt

c:\users\shiva\anaconda3\envs\dl\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\users\shiva\anaconda3\envs\dl\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\users\shiva\anaconda3\envs\dl\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\users\shiva\anaconda3\envs\dl\lib\site-packages\tensorflow\python\framework\dty

In [2]:
#Getting Dataset

from tensorflow.keras.datasets import mnist
(x_train,y_train),(x_test,y_test)=  mnist.load_data()
x = np.concatenate((x_train,x_test))
y = pd.get_dummies(np.concatenate((y_train,y_test))).values
x = x.reshape(x.shape[0],28,28,1)

11493376/11490434 [==============================] - 1s 0us/step


In [3]:
# Rotating Images in dataset
X = tf.placeholder(tf.float32,[None,28,28,1])
x1 = tf.contrib.image.rotate(X,angles = (3.14/6))
x2 = tf.contrib.image.rotate(X,angles = (-3.14/6))

The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.



In [4]:
with tf.Session() as sess:
    x1 = sess.run(x1,{X:x})
    x2 = sess.run(x2,{X:x})

In [5]:
x = np.concatenate((x,x1,x2))
y = np.concatenate((y,y,y))
x = x.reshape(x.shape[0],784)
dataset = np.concatenate((x,y),axis=1)

In [25]:
print(dataset)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [109]:
from sklearn.utils import shuffle
dataset = shuffle(dataset)
x = dataset[:,:784]
y = dataset[:,784:]

In [116]:
x = x.reshape(x.shape[0],28,28,1)

#Getting Train,Validate and Test dataset
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

from sklearn.model_selection import train_test_split
x_validate,x_test,y_validate,y_test = train_test_split(x_test,y_test,test_size=0.5)

In [119]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)
print(x_validate.shape)
print(y_validate.shape)

(147000, 28, 28, 1)
(147000, 10)
(31500, 28, 28, 1)
(31500, 10)
(31500, 28, 28, 1)
(31500, 10)


In [121]:
#Saving Dataset as npz file for training

np.savez("Dataset/train.npz",Input = x_train, Output = y_train)
np.savez("Dataset/validate.npz",Input = x_validate, Output = y_validate)
np.savez("Dataset/test.npz",Input = x_test, Output = y_test)